# Generated by Django 4.2.14 on 2024-07-19 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_author'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='post',
            name='Unique post constraint',
        ),
    ]
